Made some changes on the Error 404 page.
EmanuelGF/template-react-ui pull request #10
Opened 2021-05-03 17:44 UTC by BillNas

2021-05-03 22:20 UTC, EmanuelGF requested changes
Hi @BillNas l! 🙏
First off all let me thank you for your interest and help on the project! 👌
The 404 page looks much better!  Just a couple of things to refactor out:
1- Can you fix the spacing? 
![404](https://user-images.githubusercontent.com/25751489/116939268-fe1d3980-ac63-11eb-914a-0bba74947e0d.png)

2- On **src/App.js** the import path to **notFound** should be corrected. 

 Note: your PR includes a lot of changes to the package-lock file from your local npm install run. you can avoid this next time by stashing the package-lock changes after npm install then  doing a "pull" of any changes from the "main" branch of the "upstream" into your local repository.
Thank you again for your time spent on this.

2021-05-04 09:16 UTC, BillNas commented
I fixed the spacing. Hope it is good now. 🙏🏻

2021-05-04 10:30 UTC, EmanuelGF requested changes
Hey @BillNas  ! Hope you are doing good ✌
After having a better look at the code you summitted I spotted some other issues that I have commented on. 
Furthermore there is another issue. It looks like when committed your changes you did not sync your repo getting the latest changes and updates from the original repo. If I were to merge your pull request it would roll back the history removing some latest changes. 
It's good practice to always pull latest changes and merge before submitting your commits. If you can try to fix this it would be gold 🙂
Let me know how its going.

2021-05-04 14:40 UTC, BillNas commented on src/Components/NotFound/notFound.scss
> +	margin: 0;
I am a beginner so I don't exactly know how to handle that kind of situations like sync of a repo. 😣

2021-05-04 16:16 UTC, EmanuelGF commented
No worries ! 🙂
I will not merge this PR but I have already accepted your code changes and given attribution to you! 👌 Thank you again for your effort and help! NICE!!
If you want to keep exploring this project don't forget to pull the newest added changes from the upstream and pull them to your main on your local machine.
I suggest you go through all the guides on the CONTRIBUTION file to get a hang on git.  
Star and watch this project to get notified on more issues like this one! 
Thanks again.

2021-05-04 16:18 UTC, closed without merging